# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Certificate for site-manager TLS, managed by cert-manager.io
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: site-manager-tls
spec:
  # Secret where cert-manager will store the certificate
  secretName: site-manager-tls

  duration: 2160h # 90d
  renewBefore: 360h # 15d
  subject:
    organizations:
      - Nvidia
  commonName: carbide-rest-site-manager
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - server auth
    - client auth
  dnsNames:
    - carbide-rest-site-manager
    - carbide-rest-site-manager.carbide
    - carbide-rest-site-manager.carbide.svc.cluster.local
    - localhost
  issuerRef:
    name: carbide-ca-issuer
    kind: ClusterIssuer
    group: cert-manager.io
