# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Client certificate for workflow services (API, cloud-worker, site-worker) in carbide namespace
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: temporal-client-cert
  namespace: carbide
spec:
  secretName: temporal-client-certs
  duration: 2160h # 90 days
  renewBefore: 360h # 15 days
  subject:
    organizations:
      - NVIDIA
  commonName: temporal-client
  isCA: false
  privateKey:
    algorithm: RSA
    size: 2048
  usages:
    - client auth
  dnsNames:
    - temporal-client
    - carbide-rest-api
    - cloud-worker
    - site-worker
  issuerRef:
    name: carbide-ca-issuer
    kind: ClusterIssuer
    group: cert-manager.io
